Repository firedrakeproject/firedrake, pull requests merged in 2023-11, with the labels that each got.

#3228 small fix to documentation on interpolator
  docs/source/interpolation.rst
Labels: documentation

#3246 MG: Fix issue with multiple refinements per level
  firedrake/mg/kernels.py
Labels: bug, easy-win

#3239 Fix docs
  docs/source/conf.py
  docs/source/element_list.py
  firedrake/functionspace.py
  firedrake/functionspaceimpl.py
  firedrake/preconditioners/pmg.py
Labels: documentation, straightforward, good first issue

#3221 Docs for `variant="spectral"` on simplices
  docs/source/_static/bibliography.bib
  docs/source/variational-problems.rst
Labels: documentation

#3241 Reconstruct a FunctionSpace on a different mesh
  firedrake/functionspace.py
  firedrake/functionspaceimpl.py
  firedrake/mg/kernels.py
  firedrake/mg/ufl_utils.py
  firedrake/preconditioners/pmg.py
  tests/multigrid/test_non_nested.py
  tests/multigrid/test_poisson_gmg.py
  tests/regression/test_function_spaces.py
Labels: bug, enhancement

#3252 Fix HypreAMS/ADS setFromOptions
  firedrake/preconditioners/hypre_ads.py
  firedrake/preconditioners/hypre_ams.py
  tests/regression/test_hypre_ads.py
  tests/regression/test_hypre_ams.py
Labels: bug, easy-win

#3259 Expunge Expr.ufl_domain Part II
  docs/source/interpolation.rst
  firedrake/assemble.py
  firedrake/function.py
  firedrake/functionspaceimpl.py
  firedrake/interpolation.py
  firedrake/mg/interface.py
  firedrake/mg/kernels.py
  firedrake/mg/ufl_utils.py
  firedrake/mg/utils.py
  firedrake/output.py
  firedrake/plot.py
  firedrake/preconditioners/patch.py
  firedrake/ufl_expr.py
  tests/extrusion/test_real_tensorproduct.py
  tests/multigrid/test_non_nested.py
  tests/multigrid/test_transfer_manager.py
  tests/regression/test_auxiliary_dm.py
  tests/regression/test_helmholtz_bernstein.py
  tests/regression/test_interpolate_vs_project.py
  tests/regression/test_interpolate_zany.py
  tests/regression/test_interpolation_nodes.py
  tests/regression/test_subdomain_integrals.py
  tests/regression/test_vfs_component_bcs.py
Labels: straightforward
