Repository firedrakeproject/firedrake, pull requests merged in 2025-01, with the labels that each got.

#3932 Fix fieldsplit with `Cofunction` right hand side.
  firedrake/formmanipulation.py
  tests/firedrake/regression/test_linesmoother.py
  tests/firedrake/regression/test_matrix_free.py
  tests/firedrake/regression/test_nullspace.py
Labels: bug

#3959 Use PetscCall() instead of CHKERRQ() in tinyasm
  tinyasm/tinyasm.cpp
Labels: macOS

#3964 Temp fix for firedrake install on Mac for Xcode16
  scripts/firedrake-install
Labels: macOS

#3385 Test suite clean up
  .github/workflows/build-mac.yml
  .github/workflows/build.yml
  .github/workflows/pip-mac.yml
  .github/workflows/pip.yml
  .test_durations
  Makefile
  docs/source/download.rst
  firedrake/constant.py
  firedrake/preconditioners/patch.py
  firedrake/slate/slac/compiler.py
  firedrake/tsfc_interface.py
  pyproject.toml
  scripts/firedrake-run-split-tests
  setup.cfg
  tests/firedrake/conftest.py
  tests/firedrake/demos/test_demos_run.py
  tests/firedrake/multigrid/test_embedded_transfer.py
  tests/firedrake/multigrid/test_poisson_gmg.py
  tests/firedrake/output/test_adjoint_disk_checkpointing.py
  tests/firedrake/output/test_io_function.py
  tests/firedrake/output/test_io_mesh.py
  tests/firedrake/regression/test_dg_advection.py
  tests/firedrake/regression/test_ensembleparallelism.py
  tests/firedrake/regression/test_garbage.py
  tests/firedrake/regression/test_interpolate_cross_mesh.py
  tests/firedrake/regression/test_par_loops.py
  tests/firedrake/regression/test_restricted_function_space.py
  tests/firedrake/regression/test_stokes_hdiv_parallel.py
  tests/firedrake/regression/test_stress_elements.py
  tests/firedrake/test_0init.py
  tests/firedrake/vertexonly/test_poisson_inverse_conductivity.py
Labels: bug, enhancement, performance, macOS
