Repository firedrakeproject/firedrake, pull requests merged in 2025-07, with the labels that each got.

#4417 Remove old link from docs
  docs/source/team.ini
Labels: documentation

#4383 Speed up caching
  firedrake/interpolation.py
  firedrake/slate/slac/compiler.py
  firedrake/tsfc_interface.py
  pyop2/caching.py
  pyop2/compilation.py
  tests/pyop2/test_caching.py
Labels: performance

#4404 Recommend running firedrake-clean after updating
  docs/source/install.rst
Labels: documentation

#4448 Test `ReducedFunctional.tlm`
  .github/workflows/core.yml
  firedrake/adjoint/ensemble_reduced_functional.py
  tests/firedrake/adjoint/test_tlm.py
Labels: testing

#4451 test for early cleanup of adjoint variables
  tests/firedrake/adjoint/test_assignment.py
Labels: testing, macOS
