Repository firedrakeproject/firedrake, pull requests merged in 2025-04, with the labels that each got.

#4182 Download CMake on homebrew because PETSc release does not support 4.0
  scripts/firedrake-configure
Labels: macOS

#4199 Remove dead link to Paraview wiki
  docs/source/visualisation.rst
Labels: documentation

#4221 Remove unused PDF file
  docs/source/images/tape.pdf
Labels: documentation

#4228 Add temporary constraint on islpy
  pyproject.toml
Labels: macOS

#4247 Use more homebrew packages on Mac
  scripts/firedrake-configure
Labels: macOS

#4236 Undo pin on islpy
  pyproject.toml
Labels: macOS

#4122 Use apt for more PETSc packages on x86
  docker/Dockerfile.vanilla
  scripts/firedrake-configure
  tests/firedrake/vertexonly/test_vertex_only_mesh_generation.py
Labels: installation

#4193 Firedrake release
  .github/workflows/core.yml
  .github/workflows/docker.yml
  .github/workflows/docker_merge.yml
  .github/workflows/pr.yml
  .github/workflows/push.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/test_macos.yml
  Makefile
  docker/Dockerfile.docdeps
  docs/source/conf.py
  docs/source/documentation.rst
  docs/source/install.rst
  docs/source/zenodo.rst
  firedrake/eigensolver.py
  firedrake/mg/mesh.py
  firedrake/mg/opencascade_mh.py
  firedrake/scripts/firedrake-zenodo
  pyproject.toml
  requirements-build.txt
Labels: macOS
